### ISSUE TITLE
There should be space between this error line and search bar when access is not given.

### ISSUE THREAD

**Issue by Rakshit-gen** [krotrn/Weather#1]
![image](https://github.com/user-attachments/assets/49b92365-6f44-4a62-8c5d-f612252b4eeb)

**Comment by krotrn** [comment]
Thank you for addressing the issue with the error message spacing. The solution to add appropriate margin (m-5) between the error message and the search bar resolves the layout problem and enhances the UI. Great work on solving this!

**Comment by Rakshit-gen** [comment]
Thanks @krotrn I will make more changes whenever i find any issues. Thank you for the opportunity
